
#include "_include_header.h"

const GPIO_FIELD gpo_lists[GPO_LIST_MAX] = 
{
    { GPIO_PORTA_BASE, GPIO_PIN_4, GPIO_LVL_HI, "GPO_CS3"}, 
    { GPIO_PORTA_BASE, GPIO_PIN_5, GPIO_LVL_LO, "GPO_SCK3"},
    { GPIO_PORTA_BASE, GPIO_PIN_6, GPIO_LVL_LO, "GPO_SDI3"},
        
    { GPIO_PORTD_BASE, GPIO_PIN_0, GPIO_LVL_LO, "GPO_TEMP_ALARM3"},
    { GPIO_PORTD_BASE, GPIO_PIN_1, GPIO_LVL_HI, "GPO_SSR1"},
    { GPIO_PORTD_BASE, GPIO_PIN_2, GPIO_LVL_HI, "GPO_SSR2"},
    { GPIO_PORTD_BASE, GPIO_PIN_3, GPIO_LVL_HI, "GPO_SSR3"},
        
    { GPIO_PORTE_BASE, GPIO_PIN_4, GPIO_LVL_LO, "GPO_TEMP_ALARM1"},
    { GPIO_PORTE_BASE, GPIO_PIN_5, GPIO_LVL_LO, "GPO_TEMP_ALARM2"},
        
    { GPIO_PORTF_BASE, GPIO_PIN_2, GPIO_LVL_HI, "GPO_CS2"},
    { GPIO_PORTF_BASE, GPIO_PIN_3, GPIO_LVL_LO, "GPO_SCK2"},
        
    { GPIO_PORTG_BASE, GPIO_PIN_0, GPIO_LVL_LO, "GPO_SDI1"},
    { GPIO_PORTG_BASE, GPIO_PIN_1, GPIO_LVL_LO, "GPO_SCK1"},
    { GPIO_PORTG_BASE, GPIO_PIN_2, GPIO_LVL_HI, "GPO_CS1"},
    { GPIO_PORTG_BASE, GPIO_PIN_5, GPIO_LVL_LO, "GPO_SDI2"},

};


const GPIO_FIELD gpi_lists[GPI_LIST_MAX] = 
{
    { GPIO_PORTA_BASE, GPIO_PIN_2, GPIO_LVL_LO, "GPI_DRDY3"},
    { GPIO_PORTA_BASE, GPIO_PIN_3, GPIO_LVL_LO, "GPI_SDO3"},
    { GPIO_PORTF_BASE, GPIO_PIN_0, GPIO_LVL_LO, "GPI_DRDY2"},
    { GPIO_PORTF_BASE, GPIO_PIN_1, GPIO_LVL_LO, "GPI_SDO2"},
    { GPIO_PORTG_BASE, GPIO_PIN_4, GPIO_LVL_LO, "GPI_DRDY1"},
    { GPIO_PORTG_BASE, GPIO_PIN_3, GPIO_LVL_LO, "GPI_SDO1"},

};


